config/routes.rb
Rails.application.routes.draw do

  resources :users do
    scope module: :users do
      resources :tasks do
        collection do
          get :search
        end
        member do
          get :done
        end
      end
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get :fetch_user
      end
      scope module: :users do
        resources :tasks do
          scope module: :tasks do
            resources :comments
          end
        end
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'

  get 'welcome/index'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :created_tasks, foreign_key: :creator_id, class_name: 'Task', dependent: :destroy
  has_many :assigned_tasks, foreign_key: :assigned_to_id, class_name: 'Task', dependent: :destroy
  has_many :comments, class_name: 'Task::Comment'

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, email: true, uniqueness: true
  validates :password_digest, presence: true

  mount_uploader :avatar, AvatarUploader

  has_secure_password
end

app/models/user/task.rb
require 'elasticsearch/model'

class User::Task < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :creator, class_name: 'User'
  belongs_to :assigned_to, class_name: 'User'
  has_many :comments, :class_name => 'Comment'
  accepts_nested_attributes_for :comments, :reject_if => :all_blank, :allow_destroy => true

  state_machine initial: :opened do
    state :opened
    state :closed

    event :open do
      transition [:closed] => :opened
    end

    event :close do
      transition [:opened] => :closed
    end
  end

  def self.search_with_elasticsearch(*args)
    __elasticsearch__.search(*args)
  end
end

app/models/user/task/comment.rb
class User::Task::Comment < ActiveRecord::Base
  belongs_to :task, :class_name => 'Task'
  belongs_to :user
end

app/controllers/admin/users/tasks/comments_controller.rb
class Admin::Users::Tasks::CommentsController < ApplicationController
  before_action :find_user
  before_action :find_task

  def new
    @comment = @task.comments.build(user_id: @user.id)
  end

  def create
    @comment = @task.comments.new(comment_params)

    if @comment.save
      flash[:success] = "Comment added"
      redirect_to admin_user_task_comment_path(@user, @task, @comment)
    else
      render :new
    end
  end

  def index
    @comments = @task.comments
  end

  def show
    @comment = User::Task::Comment.find(params[:id])
  end

  def edit
    @comment = User::Task::Comment.find(params[:id])
  end

  def update
    @comment = User::Task::Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:success] = "Comment updated"
      redirect_to admin_user_task_comment_path(@user, @task, @comment)
    else
      render :edit
    end
  end

  def destroy
    @comment = User::Task::Comment.find(params[:id])

    @comment.destroy

    redirect_to admin_user_task_comments_path(@user, @task)
  end

  private
  def comment_params
    params.require(:user_task_comment).permit(:content, :user_id, :user, :task_id, :task)
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_task
    @task = User::Task.find(params[:task_id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :get_user, except: [ :index, :fetch_user ]

  def index
    @search = User.ransack(params[:q])
    @users = @search.result(distinct: true)
  end

  def edit
  end

  def update
    @user = @user.becomes AdminUserEditType
    if @user.update(params[:user])
      flash[:success] = "User #{@user.name} is updated"
      redirect_to admin_users_path(@user)
    else
      flash[:danger] = "User isn't updated"
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  def fetch_user
    if params[:id].present?
      @users = User.where(id: params[:id])
    else
      index
    end
    respond_to do |format|
      format.js
    end
  end

  private
  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/tasks_controller.rb
class Users::TasksController < ApplicationController
  before_action :get_user
  before_action :find_task, only: [ :show, :edit, :destroy, :done ]

  def index
    @created_tasks = @user.created_tasks
    @assigned_tasks = @user.assigned_tasks
  end

  def new
    @task = @user.created_tasks.build
  end

  def show
  end

  def create
    @task = User::TaskCreateType.new(params[:user_task])
    if @task.save
      flash[:success] = "Task added"
      redirect_to user_task_path(@user, @task)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @task = User::TaskCreateType.find(params[:id])
    if @task.update(params[:user_task])
      flash[:success] = "Task updated"
      redirect_to user_task_path(@user, @task)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to @user
  end

  def done
    if @task.close
      flash[:success] = "Task is closed"
    else
      flash[:danger] = "Task is not closed"
    end
    redirect_to user_task_path @user, @task
  end

  def search
    query = params[:q]
    if query.present?
      tasks = User::Task.search_with_elasticsearch(query).records
      @created_tasks = tasks.where(creator_id: @user.id)
      @assigned_tasks = tasks.where(assigned_to_id: @user.id)
    else
      @created_tasks = @user.created_tasks
      @assigned_tasks = @user.assigned_tasks
    end

    respond_to do |format|
      format.js
    end
  end

  private
  def get_user
    @user = User.find(params[:user_id])
  end

  def find_task
    @task = User::Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = UserRegistrationType.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = UserRegistrationType.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Task Manager!"
      redirect_to @user
    else
      render :new
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_items_list.html.haml
%table.table
  %thead
    %tr
      %th
        - if search.present?
          = sort_link(search, :name)
        -else
          = "Name"
      %th
        - if search.present?
          = sort_link(search, :email)
        -else
          = "Email"
      %th Edit
      %th Destroy
  - items.each do |user|
    %tbody
      %tr
        %td
          = user.name
        %td
          = user.email
        %td
          = link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-success'
        %td
          = link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/admin/users/_select_user.html.haml
= select_tag :id, options_for_select(@users.collect { |u| [u.name, u.id] }), class: 'form-control', data: { remote: true, url: fetch_user_admin_users_path }, prompt: "don't selected"

app/views/admin/users/edit.html.haml
%h1 Admin::Users#edit
= simple_form_for(@user, url: admin_user_path(@user), :html => {:multipart => true}) do |f|
  = f.input :name
  = f.input :email
  = f.input :avatar, as: :image_preview
  = f.button :submit

app/views/admin/users/fetch_user.js.haml
$('#items_grid').html("#{escape_javascript(render(partial: 'items_list', locals: { items: @users, search: @search }))}");

app/views/admin/users/index.html.haml
%h1 Admin::Users#index
.grid
  = render 'select_user'
  = simple_form_for @search, url: admin_users_path, method: :get do |f|
    = f.input :name_cont, placeholder: 'name', label: false
    = f.input :email_cont, placeholder: 'email', label: false
    = f.button :submit, 'Search'
  #items_grid
    = render partial: 'items_list', locals: { items: @users, search: @search }