config/routes.rb
Rails.application.routes.draw do

  resources :users do
    scope module: :users do
      resources :tasks do
        collection do
          get :search
        end
        member do
          get :done
        end
      end
    end
  end

  namespace :admin do
    resources :users do
      collection do
        get :fetch_user
      end
      scope module: :users do
        resources :tasks do
          scope module: :tasks do
            resources :comments
          end
        end
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'

  get 'welcome/index'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Task Manager | #{yield(:title)}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse
      .navbar-inner
        .container
          = link_to "Task Manager", root_path, id: "logo", class: "navbar-brand"
          .nav-collapse.navbar-right
            %ul.list-inline
              %li
                %span.label= link_to "Home", root_path, class: "navbar-brand"
              - if sign_in?
                %li
                  %span.label= link_to "Sign out", signout_path, method: :delete, class: "navbar-brand"
              - else
                %li
                  %span.label= link_to "Registration", signup_path, class: "navbar-brand"
                %li
                  %span.label= link_to "Sign in", signin_path, class: "navbar-brand"
    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = debug(params) if Rails.env.development?